<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title><?= $this->title == null ? "Save" : $this->title." | Save"; ?></title> 
        
        <style>
            .btnHerramientas{
                width: 400px;
            }
            .mensaje{
                display: none;
                position: fixed;
                right: 0;
                z-index:100;
                /*top:0;
                left:0;
                width: 100%;*/

            }

            @media (min-width: 768px) {
                .sidebar-nav .navbar .navbar-collapse {
                    padding: 0;
                    max-height: none;
                }
                .sidebar-nav .navbar ul {
                    float: none;
                }
                /*  .sidebar-nav .navbar ul:not {
                    display: block;
                  }*/
                .sidebar-nav .navbar li {
                    float: none;
                    display: block;
                }
                .sidebar-nav .navbar li a {
                    padding-top: 12px;
                    padding-bottom: 12px;
                }
            }
            
            /***/
            * {
                @include box-sizing(border-box);
              }

              $pad: 30px;

              .grid {
                background: white;
                margin: 0 0 $pad 0;

                &:after {
                  /* Or @extend clearfix */
                  content: "";
                  display: table;
                  clear: both;
                }
              }

              [class*='cols-'] {
                float: left;
                padding-right: $pad;
                .grid &:last-of-type {
                  padding-right: 0;
                }
              }
              .cols-2-3 {
                width: 66.66%;
              }
              .cols-1-3 {
                width: 33.33%;
              }
              .cols-1-2 {
                width: 50%;
              }
              .cols-1-4 {
                width: 25%;
              }
              .cols-1-8 {
                width: 12.5%;
              }

              /* Opt-in outside padding */
              .grid-pad {
                padding: $pad 0 $pad $pad;
                [class*='cols-']:last-of-type {
                  padding-right: $pad;
                }
              }
              .chart {
                width: 100%; 
                height: 600px;
              }
        </style>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <!--<link rel="stylesheet" href="../index/css/bootstrap.min.css">-->
        <script>
            var CONTROLLERPATH = "<?= $this->controllerPath ?>";
            var BASE = "<?= BASE ?>";
            var BASEJS = "<?= "http://$_SERVER[HTTP_HOST]/" ?>";
        </script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        

        
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>



        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>

        <link rel="stylesheet" href="<?= BASE ?>css/nprogress.css"/>
        <script type="text/javascript" src="<?= BASE ?>libs/js/nprogress.js"></script>
        
        <script src='<?= BASE ?>libs/js/validateaddons.js'></script>

        <?php
        foreach ($this->jsScripts as $value) {
            echo "<script src='$this->viewPath/" . "js/$view/$value.js'></script>";
        }
        ?>

        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript" src="<?= BASE ?>libs/js/graphs.js"></script> 
        <?php if(isset($this->validacion)):?>
        <script>
            $(document).ready(function(){
                $("form").validate({
                    rules:
                        <?=$this->validacion?>
                   
                })
            })
        </script>
        <?php endif;?>
    </head>
    <body>

        <div id="dialog-confirm" >  
            <p>  		
                <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">  
                </span>¿Está seguro de eliminar su cuenta?</p></div>
        <br/>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <a href="<?= BASE?>">
                        <img src="<?= BASE ?>/img/logo.png"/>
                    </a>



                    <?php if ($this->barmenu) { ?>
                        <div class="sidebar-nav">

                            <div class="navbar navbar-default" role="navigation">
                                <!-------->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <span class="visible-xs navbar-brand">Menú </span>
                                </div>
                                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                                    <!-------------------->
                                    <ul class="nav navbar-nav">
                                        <?php for ($i = 0; $i < count($this->barmenu); $i++) { ?>	
                                            <?php
                                            $active = "";
                                            if ("http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" === $this->barmenu[$i]["url"]) {
                                                $active = " active ";
                                            }
//                                            echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"."=".$this->barmenu[$i]["url"];
//                                            echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"===$this->barmenu[$i]["url"];
                                            ?>
                                            <li class="<?= $active ?>" ><a href="<?= $this->barmenu[$i]["url"] ?>"><?= $this->barmenu[$i]["descripcion"] ?></a></li>         		 
                                        <?php } ?>
                                    </ul>
                                    <!---------------------------------------------->
                                </div><!--/.nav-collapse -->
                                <!---->
                            </div>

                        </div>
                    <?php } ?>
                </div>
                <div class=" col-sm-9">
                    <!--                    <div
                                            class="fb-like"
                                            data-share="true"
                                            data-width="450"
                                            data-show-faces="true">
                                        </div>-->

                    <?php if ($this->barmenu2) { ?>
                        <div class="">

                            <div class="navbar navbar-inverse" role="navigation">
                                <!-------->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <span class="visible-xs navbar-brand">Menú </span>
                                </div>
                                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                                    <!-------------------->
                                    <ul class="nav navbar-nav">
                                        <?php for ($i = 0; $i < count($this->barmenu2); $i++) { ?>
                                            <?php
                                            $active = "";
                                            if ("http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" === $this->barmenu2[$i]["url"]) {
                                                $active = " active ";
                                            }
                                            ?>
                                            <li  class="<?= $active ?>"><a href="<?= $this->barmenu2[$i]["url"] ?>"><?= $this->barmenu2[$i]["descripcion"] ?></a></li>         		 
                                        <?php } ?>
                                    </ul>
                                    <!---------------------------------------------->
                                </div><!--/.nav-collapse -->
                                <!---->
                            </div>

                        </div>
                    <?php } ?>

                    <br/>
                    <?= $this->title == null ? "" : "<h1>$this->title</h1>" ?>
                    <?=
                    $this->mensaje == null ? "" : "<div class='alert alert-info'>$this->mensaje</div>"?>
